// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetSystemStatusApiV1SystemStatusGetData, GetSystemStatusApiV1SystemStatusGetResponses, HealthLiveHealthLiveGetData, HealthLiveHealthLiveGetResponses, HealthReadyHealthReadyGetData, HealthReadyHealthReadyGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get public system status
 */
export const getSystemStatusApiV1SystemStatusGet = <ThrowOnError extends boolean = false>(options?: Options<GetSystemStatusApiV1SystemStatusGetData, ThrowOnError>): RequestResult<GetSystemStatusApiV1SystemStatusGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetSystemStatusApiV1SystemStatusGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/system/status',
    ...options
});

/**
 * Liveness probe
 */
export const healthLiveHealthLiveGet = <ThrowOnError extends boolean = false>(options?: Options<HealthLiveHealthLiveGetData, ThrowOnError>): RequestResult<HealthLiveHealthLiveGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthLiveHealthLiveGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/health/live',
    ...options
});

/**
 * Readiness probe
 */
export const healthReadyHealthReadyGet = <ThrowOnError extends boolean = false>(options?: Options<HealthReadyHealthReadyGetData, ThrowOnError>): RequestResult<HealthReadyHealthReadyGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthReadyHealthReadyGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/health/ready',
    ...options
});
