// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * LiveStatus
 */
export type LiveStatus = {
    /**
     * Status
     */
    status: 'alive';
};

/**
 * ReadinessStatus
 */
export type ReadinessStatus = {
    /**
     * Status
     */
    status: 'ready' | 'unavailable';
    /**
     * Checks
     */
    checks: {
        [key: string]: string;
    };
};

/**
 * ResponseModel[SystemStatus]
 */
export type ResponseModelSystemStatus = {
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    data: SystemStatus;
    /**
     * Request Id
     */
    request_id: string;
};

/**
 * SystemStatus
 */
export type SystemStatus = {
    /**
     * Status
     */
    status: 'available' | 'unavailable';
};

export type GetSystemStatusApiV1SystemStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/status';
};

export type GetSystemStatusApiV1SystemStatusGetResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelSystemStatus;
};

export type GetSystemStatusApiV1SystemStatusGetResponse = GetSystemStatusApiV1SystemStatusGetResponses[keyof GetSystemStatusApiV1SystemStatusGetResponses];

export type HealthLiveHealthLiveGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type HealthLiveHealthLiveGetResponses = {
    /**
     * Successful Response
     */
    200: LiveStatus;
};

export type HealthLiveHealthLiveGetResponse = HealthLiveHealthLiveGetResponses[keyof HealthLiveHealthLiveGetResponses];

export type HealthReadyHealthReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type HealthReadyHealthReadyGetResponses = {
    /**
     * Successful Response
     */
    200: ReadinessStatus;
};

export type HealthReadyHealthReadyGetResponse = HealthReadyHealthReadyGetResponses[keyof HealthReadyHealthReadyGetResponses];
