// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AccountDeleteIn
 */
export type AccountDeleteIn = {
    /**
     * Current Password
     *
     * 当前密码，最多 64 个字符
     */
    current_password: string;
};

/**
 * ActionResult
 */
export type ActionResult = {
    /**
     * Completed
     *
     * 操作是否已经完成
     */
    completed?: boolean;
};

/**
 * AdminAuthSessionOut
 */
export type AdminAuthSessionOut = {
    /**
     * 当前认证主体信息
     */
    principal: AdminRead;
    /**
     * Session Id
     *
     * 登录会话唯一标识
     */
    session_id: string;
    /**
     * Access Expires At
     *
     * 访问凭据过期时间
     */
    access_expires_at: string;
    /**
     * Idle Expires At
     *
     * 会话空闲过期时间
     */
    idle_expires_at: string;
    /**
     * Absolute Expires At
     *
     * 会话绝对过期时间
     */
    absolute_expires_at: string;
};

/**
 * AdminBulkStatusUpdateIn
 */
export type AdminBulkStatusUpdateIn = {
    /**
     * Admin Ids
     *
     * 待批量更新状态的管理员唯一标识列表
     */
    admin_ids: Array<string>;
    /**
     * Is Active
     *
     * 资源当前是否启用
     */
    is_active: boolean;
};

/**
 * AdminConfirmIn
 */
export type AdminConfirmIn = {
    /**
     * Current Password
     *
     * 当前密码，最多 64 个字符
     */
    current_password: string;
    /**
     * 操作代码
     */
    action: ConfirmationAction;
};

/**
 * AdminConfirmOut
 */
export type AdminConfirmOut = {
    /**
     * Confirmation Token
     *
     * 敏感操作短期确认凭据
     */
    confirmation_token: string;
    /**
     * 操作代码
     */
    action: ConfirmationAction;
    /**
     * Expires At
     *
     * 凭据过期时间
     */
    expires_at: string;
};

/**
 * AdminCreateIn
 */
export type AdminCreateIn = {
    /**
     * Username
     *
     * 登录用户名
     */
    username: string;
    /**
     * Initial Password
     *
     * 初始密码，长度为 6 至 64 个字符
     */
    initial_password: string;
    /**
     * Display Name
     *
     * 展示名称
     */
    display_name?: string | null;
    /**
     * Is Active
     *
     * 资源当前是否启用
     */
    is_active?: boolean;
    /**
     * Is Superuser
     *
     * 管理员是否拥有超级管理员身份
     */
    is_superuser?: boolean;
    /**
     * Role Ids
     *
     * 分配给管理员的角色唯一标识列表
     */
    role_ids?: Array<string>;
};

/**
 * AdminLoginIn
 */
export type AdminLoginIn = {
    /**
     * Username
     *
     * 登录用户名
     */
    username: string;
    /**
     * Password
     *
     * 登录密码，最多 64 个字符
     */
    password: string;
};

/**
 * AdminProfileUpdateIn
 */
export type AdminProfileUpdateIn = {
    /**
     * Display Name
     *
     * 展示名称
     */
    display_name?: string | null;
    /**
     * Avatar
     *
     * 管理员头像 URL 或站内资源路径
     */
    avatar?: string | null;
};

/**
 * AdminRead
 */
export type AdminRead = {
    /**
     * Id
     *
     * 资源唯一标识
     */
    id: string;
    /**
     * Username
     *
     * 登录用户名
     */
    username: string;
    /**
     * Display Name
     *
     * 展示名称
     */
    display_name: string | null;
    /**
     * Avatar
     *
     * 管理员头像 URL 或站内资源路径
     */
    avatar?: string | null;
    /**
     * Is Active
     *
     * 资源当前是否启用
     */
    is_active: boolean;
    /**
     * Is Superuser
     *
     * 管理员是否拥有超级管理员身份
     */
    is_superuser: boolean;
    /**
     * Roles
     *
     * 管理员当前拥有的角色列表
     */
    roles: Array<RoleSummary>;
    /**
     * Permissions
     *
     * 当前主体拥有的权限代码列表
     */
    permissions: Array<string>;
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string;
    /**
     * Updated At
     *
     * 最近更新时间
     */
    updated_at: string;
};

/**
 * AdminRoleAssignIn
 */
export type AdminRoleAssignIn = {
    /**
     * Role Ids
     *
     * 分配给管理员的角色唯一标识列表
     */
    role_ids: Array<string>;
};

/**
 * AdminUpdateIn
 */
export type AdminUpdateIn = {
    /**
     * Display Name
     *
     * 展示名称
     */
    display_name?: string | null;
    /**
     * Avatar
     *
     * 管理员头像 URL 或站内资源路径
     */
    avatar?: string | null;
    /**
     * Is Superuser
     *
     * 管理员是否拥有超级管理员身份
     */
    is_superuser?: boolean | null;
};

/**
 * AssetRead
 */
export type AssetRead = {
    /**
     * Id
     *
     * 文件资产唯一标识
     */
    id: string;
    /**
     * 上传主体类型
     */
    uploader_type: UploaderType;
    /**
     * Uploader Id
     *
     * 上传主体唯一标识，系统任务可为空
     */
    uploader_id: string | null;
    /**
     * Storage Driver
     *
     * 保存文件的存储驱动代码
     */
    storage_driver: string;
    /**
     * File Key
     *
     * 存储驱动中的相对文件键
     */
    file_key: string;
    /**
     * Original Name
     *
     * 上传时经过路径剥离的原始文件名
     */
    original_name: string;
    /**
     * Mime Type
     *
     * 服务端探测得到的真实 MIME 类型
     */
    mime_type: string;
    /**
     * File Size
     *
     * 文件大小，单位为字节
     */
    file_size: number;
    /**
     * File Hash
     *
     * 文件内容的 SHA-256 哈希值
     */
    file_hash: string;
    /**
     * Url
     *
     * 文件的公开访问 URL 或站内路径
     */
    url: string;
    /**
     * 受控的文件使用场景
     */
    scene: UploadScene;
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string;
    /**
     * Updated At
     *
     * 最近更新时间
     */
    updated_at: string;
};

/**
 * AuditEventRead
 */
export type AuditEventRead = {
    /**
     * Id
     *
     * 资源唯一标识
     */
    id: string;
    /**
     * Actor Id
     *
     * 操作管理员唯一标识
     */
    actor_id: string | null;
    /**
     * Action
     *
     * 操作代码
     */
    action: string;
    /**
     * Target Type
     *
     * 操作目标类型
     */
    target_type: string;
    /**
     * Target Id
     *
     * 操作目标唯一标识
     */
    target_id: string | null;
    /**
     * Result
     *
     * 操作结果代码
     */
    result: string;
    /**
     * Changed Fields
     *
     * 本次操作涉及的字段摘要
     */
    changed_fields: {
        [key: string]: unknown;
    };
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
    /**
     * Occurred At
     *
     * 事件发生时间
     */
    occurred_at: string;
    /**
     * Completed At
     *
     * 操作完成时间
     */
    completed_at: string | null;
};

/**
 * Body_upload_asset_api_v1_assets_upload_post
 */
export type BodyUploadAssetApiV1AssetsUploadPost = {
    /**
     * File
     *
     * 需要上传的文件
     */
    file: Blob | File;
    /**
     * 受控的文件使用场景
     */
    scene: UploadScene;
};

/**
 * ConfirmationAction
 */
export type ConfirmationAction = 'users:disable' | 'users:credentials:reset' | 'users:sessions:revoke' | 'admins:create' | 'admins:superuser:change' | 'admins:status:change' | 'admins:credentials:reset' | 'admins:roles:assign' | 'admins:sessions:revoke' | 'roles:delete' | 'roles:permissions:assign' | 'assets:delete';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     *
     * 请求参数校验错误详情列表
     */
    detail?: Array<ValidationError>;
};

/**
 * LiveStatus
 */
export type LiveStatus = {
    /**
     * Status
     *
     * 当前状态代码
     */
    status: 'alive';
};

/**
 * LoginEventRead
 */
export type LoginEventRead = {
    /**
     * Id
     *
     * 资源唯一标识
     */
    id: string;
    /**
     * Principal Type
     *
     * 认证主体类型
     */
    principal_type: string;
    /**
     * Principal Id
     *
     * 认证主体唯一标识
     */
    principal_id: string | null;
    /**
     * Event Type
     *
     * 安全事件类型代码
     */
    event_type: string;
    /**
     * Succeeded
     *
     * 安全事件是否成功
     */
    succeeded: boolean;
    /**
     * Reason Code
     *
     * 事件原因代码
     */
    reason_code: string;
    /**
     * Ip Address
     *
     * 请求来源 IP 地址
     */
    ip_address: string | null;
    /**
     * User Agent Summary
     *
     * 脱敏后的客户端标识摘要
     */
    user_agent_summary: string | null;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
    /**
     * Occurred At
     *
     * 事件发生时间
     */
    occurred_at: string;
};

/**
 * PageResult[AdminRead]
 */
export type PageResultAdminRead = {
    /**
     * Items
     *
     * 当前分页中的资源列表
     */
    items: Array<AdminRead>;
    /**
     * Page
     *
     * 当前页码，从 1 开始
     */
    page: number;
    /**
     * Page Size
     *
     * 每页资源数量
     */
    page_size: number;
    /**
     * Total
     *
     * 符合条件的资源总数
     */
    total: number;
    /**
     * Total Pages
     *
     * 符合条件的总页数
     */
    total_pages: number;
};

/**
 * PageResult[AssetRead]
 */
export type PageResultAssetRead = {
    /**
     * Items
     *
     * 当前分页中的资源列表
     */
    items: Array<AssetRead>;
    /**
     * Page
     *
     * 当前页码，从 1 开始
     */
    page: number;
    /**
     * Page Size
     *
     * 每页资源数量
     */
    page_size: number;
    /**
     * Total
     *
     * 符合条件的资源总数
     */
    total: number;
    /**
     * Total Pages
     *
     * 符合条件的总页数
     */
    total_pages: number;
};

/**
 * PageResult[AuditEventRead]
 */
export type PageResultAuditEventRead = {
    /**
     * Items
     *
     * 当前分页中的资源列表
     */
    items: Array<AuditEventRead>;
    /**
     * Page
     *
     * 当前页码，从 1 开始
     */
    page: number;
    /**
     * Page Size
     *
     * 每页资源数量
     */
    page_size: number;
    /**
     * Total
     *
     * 符合条件的资源总数
     */
    total: number;
    /**
     * Total Pages
     *
     * 符合条件的总页数
     */
    total_pages: number;
};

/**
 * PageResult[LoginEventRead]
 */
export type PageResultLoginEventRead = {
    /**
     * Items
     *
     * 当前分页中的资源列表
     */
    items: Array<LoginEventRead>;
    /**
     * Page
     *
     * 当前页码，从 1 开始
     */
    page: number;
    /**
     * Page Size
     *
     * 每页资源数量
     */
    page_size: number;
    /**
     * Total
     *
     * 符合条件的资源总数
     */
    total: number;
    /**
     * Total Pages
     *
     * 符合条件的总页数
     */
    total_pages: number;
};

/**
 * PageResult[RequestLogRead]
 */
export type PageResultRequestLogRead = {
    /**
     * Items
     *
     * 当前分页中的资源列表
     */
    items: Array<RequestLogRead>;
    /**
     * Page
     *
     * 当前页码，从 1 开始
     */
    page: number;
    /**
     * Page Size
     *
     * 每页资源数量
     */
    page_size: number;
    /**
     * Total
     *
     * 符合条件的资源总数
     */
    total: number;
    /**
     * Total Pages
     *
     * 符合条件的总页数
     */
    total_pages: number;
};

/**
 * PageResult[RoleRead]
 */
export type PageResultRoleRead = {
    /**
     * Items
     *
     * 当前分页中的资源列表
     */
    items: Array<RoleRead>;
    /**
     * Page
     *
     * 当前页码，从 1 开始
     */
    page: number;
    /**
     * Page Size
     *
     * 每页资源数量
     */
    page_size: number;
    /**
     * Total
     *
     * 符合条件的资源总数
     */
    total: number;
    /**
     * Total Pages
     *
     * 符合条件的总页数
     */
    total_pages: number;
};

/**
 * PageResult[SessionRead]
 */
export type PageResultSessionRead = {
    /**
     * Items
     *
     * 当前分页中的资源列表
     */
    items: Array<SessionRead>;
    /**
     * Page
     *
     * 当前页码，从 1 开始
     */
    page: number;
    /**
     * Page Size
     *
     * 每页资源数量
     */
    page_size: number;
    /**
     * Total
     *
     * 符合条件的资源总数
     */
    total: number;
    /**
     * Total Pages
     *
     * 符合条件的总页数
     */
    total_pages: number;
};

/**
 * PageResult[UserPrincipalOut]
 */
export type PageResultUserPrincipalOut = {
    /**
     * Items
     *
     * 当前分页中的资源列表
     */
    items: Array<UserPrincipalOut>;
    /**
     * Page
     *
     * 当前页码，从 1 开始
     */
    page: number;
    /**
     * Page Size
     *
     * 每页资源数量
     */
    page_size: number;
    /**
     * Total
     *
     * 符合条件的资源总数
     */
    total: number;
    /**
     * Total Pages
     *
     * 符合条件的总页数
     */
    total_pages: number;
};

/**
 * PasswordChangeIn
 */
export type PasswordChangeIn = {
    /**
     * Current Password
     *
     * 当前密码，最多 64 个字符
     */
    current_password: string;
    /**
     * New Password
     *
     * 新密码，长度为 6 至 64 个字符
     */
    new_password: string;
};

/**
 * PasswordResetIn
 */
export type PasswordResetIn = {
    /**
     * New Password
     *
     * 新密码，长度为 6 至 64 个字符
     */
    new_password: string;
};

/**
 * PermissionRead
 */
export type PermissionRead = {
    /**
     * Id
     *
     * 资源唯一标识
     */
    id: string;
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Name
     *
     * 资源名称
     */
    name: string;
    /**
     * Description
     *
     * 资源说明文本
     */
    description: string | null;
    /**
     * Is Active
     *
     * 资源当前是否启用
     */
    is_active: boolean;
    /**
     * Catalog Version
     *
     * 权限目录版本
     */
    catalog_version: string;
};

/**
 * ReadinessStatus
 */
export type ReadinessStatus = {
    /**
     * Status
     *
     * 当前状态代码
     */
    status: 'ready' | 'unavailable';
    /**
     * Checks
     *
     * 各项就绪依赖的安全状态摘要
     */
    checks: {
        [key: string]: string;
    };
};

/**
 * RefreshSessionOut
 */
export type RefreshSessionOut = {
    /**
     * Session Id
     *
     * 登录会话唯一标识
     */
    session_id: string;
    /**
     * Access Expires At
     *
     * 访问凭据过期时间
     */
    access_expires_at: string;
    /**
     * Idle Expires At
     *
     * 会话空闲过期时间
     */
    idle_expires_at: string;
    /**
     * Absolute Expires At
     *
     * 会话绝对过期时间
     */
    absolute_expires_at: string;
};

/**
 * RequestLogRead
 */
export type RequestLogRead = {
    /**
     * Id
     *
     * 资源唯一标识
     */
    id: string;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
    /**
     * Trace Id
     *
     * 用于关联跨组件调用链的唯一标识
     */
    trace_id: string;
    /**
     * Method
     *
     * HTTP 请求方法
     */
    method: string;
    /**
     * Route Template
     *
     * 规范化后的 API 路由模板
     */
    route_template: string;
    /**
     * Status Code
     *
     * HTTP 响应状态码
     */
    status_code: number;
    /**
     * Duration Ms
     *
     * 请求处理耗时，单位为毫秒
     */
    duration_ms: number;
    /**
     * Principal Type
     *
     * 认证主体类型
     */
    principal_type: string | null;
    /**
     * Release Version
     *
     * 处理请求的应用发布版本
     */
    release_version: string | null;
    /**
     * Occurred At
     *
     * 事件发生时间
     */
    occurred_at: string;
    /**
     * Request Body
     *
     * 脱敏并截断后的错误 JSON 请求体
     */
    request_body: string | null;
};

/**
 * ResponseModel[ActionResult]
 */
export type ResponseModelActionResult = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: ActionResult;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[AdminAuthSessionOut]
 */
export type ResponseModelAdminAuthSessionOut = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: AdminAuthSessionOut;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[AdminConfirmOut]
 */
export type ResponseModelAdminConfirmOut = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: AdminConfirmOut;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[AdminRead]
 */
export type ResponseModelAdminRead = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: AdminRead;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[AssetRead]
 */
export type ResponseModelAssetRead = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: AssetRead;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[PageResult[AdminRead]]
 */
export type ResponseModelPageResultAdminRead = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: PageResultAdminRead;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[PageResult[AssetRead]]
 */
export type ResponseModelPageResultAssetRead = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: PageResultAssetRead;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[PageResult[AuditEventRead]]
 */
export type ResponseModelPageResultAuditEventRead = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: PageResultAuditEventRead;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[PageResult[LoginEventRead]]
 */
export type ResponseModelPageResultLoginEventRead = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: PageResultLoginEventRead;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[PageResult[RequestLogRead]]
 */
export type ResponseModelPageResultRequestLogRead = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: PageResultRequestLogRead;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[PageResult[RoleRead]]
 */
export type ResponseModelPageResultRoleRead = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: PageResultRoleRead;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[PageResult[SessionRead]]
 */
export type ResponseModelPageResultSessionRead = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: PageResultSessionRead;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[PageResult[UserPrincipalOut]]
 */
export type ResponseModelPageResultUserPrincipalOut = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: PageResultUserPrincipalOut;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[RefreshSessionOut]
 */
export type ResponseModelRefreshSessionOut = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: RefreshSessionOut;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[RoleRead]
 */
export type ResponseModelRoleRead = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: RoleRead;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[SystemStatus]
 */
export type ResponseModelSystemStatus = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: SystemStatus;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[UserAuthSessionOut]
 */
export type ResponseModelUserAuthSessionOut = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: UserAuthSessionOut;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[UserPrincipalOut]
 */
export type ResponseModelUserPrincipalOut = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * 响应业务数据
     */
    data: UserPrincipalOut;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[bool]
 */
export type ResponseModelBool = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * Data
     *
     * 响应业务数据
     */
    data: boolean;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[list[AdminRead]]
 */
export type ResponseModelListAdminRead = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * Data
     *
     * 响应业务数据
     */
    data: Array<AdminRead>;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * ResponseModel[list[PermissionRead]]
 */
export type ResponseModelListPermissionRead = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Message
     *
     * 面向调用方的中文结果消息
     */
    message: string;
    /**
     * Data
     *
     * 响应业务数据
     */
    data: Array<PermissionRead>;
    /**
     * Request Id
     *
     * 用于定位本次请求的唯一标识
     */
    request_id: string;
};

/**
 * RoleCreateIn
 */
export type RoleCreateIn = {
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Name
     *
     * 资源名称
     */
    name: string;
    /**
     * Description
     *
     * 资源说明文本
     */
    description?: string | null;
    /**
     * Is Active
     *
     * 资源当前是否启用
     */
    is_active?: boolean;
};

/**
 * RolePermissionAssignIn
 */
export type RolePermissionAssignIn = {
    /**
     * Permission Codes
     *
     * 分配给角色的权限代码列表
     */
    permission_codes: Array<string>;
};

/**
 * RoleRead
 */
export type RoleRead = {
    /**
     * Id
     *
     * 资源唯一标识
     */
    id: string;
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Name
     *
     * 资源名称
     */
    name: string;
    /**
     * Description
     *
     * 资源说明文本
     */
    description: string | null;
    /**
     * Is Active
     *
     * 资源当前是否启用
     */
    is_active: boolean;
    /**
     * Permissions
     *
     * 当前主体拥有的权限代码列表
     */
    permissions: Array<string>;
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string;
    /**
     * Updated At
     *
     * 最近更新时间
     */
    updated_at: string;
};

/**
 * RoleSummary
 */
export type RoleSummary = {
    /**
     * Id
     *
     * 资源唯一标识
     */
    id: string;
    /**
     * Code
     *
     * 稳定程序代码
     */
    code: string;
    /**
     * Name
     *
     * 资源名称
     */
    name: string;
};

/**
 * RoleUpdateIn
 */
export type RoleUpdateIn = {
    /**
     * Name
     *
     * 资源名称
     */
    name?: string | null;
    /**
     * Description
     *
     * 资源说明文本
     */
    description?: string | null;
    /**
     * Is Active
     *
     * 资源当前是否启用
     */
    is_active?: boolean | null;
};

/**
 * SessionRead
 */
export type SessionRead = {
    /**
     * Id
     *
     * 资源唯一标识
     */
    id: string;
    /**
     * Device Name
     *
     * 登录设备名称
     */
    device_name: string | null;
    /**
     * Ip Masked
     *
     * 脱敏后的请求来源 IP 地址
     */
    ip_masked: string | null;
    /**
     * User Agent Summary
     *
     * 脱敏后的客户端标识摘要
     */
    user_agent_summary: string | null;
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string;
    /**
     * Last Seen At
     *
     * 会话最近活动时间
     */
    last_seen_at: string;
    /**
     * Idle Expires At
     *
     * 会话空闲过期时间
     */
    idle_expires_at: string;
    /**
     * Absolute Expires At
     *
     * 会话绝对过期时间
     */
    absolute_expires_at: string;
    /**
     * Is Current
     *
     * 是否为当前登录会话
     */
    is_current: boolean;
    /**
     * Revoked At
     *
     * 会话撤销时间
     */
    revoked_at: string | null;
};

/**
 * StatusUpdateIn
 */
export type StatusUpdateIn = {
    /**
     * Is Active
     *
     * 资源当前是否启用
     */
    is_active: boolean;
};

/**
 * SystemStatus
 */
export type SystemStatus = {
    /**
     * Status
     *
     * 当前状态代码
     */
    status: 'available' | 'unavailable';
};

/**
 * UploadScene
 */
export type UploadScene = 'avatar' | 'article' | 'product' | 'document' | 'attachment' | 'temp';

/**
 * UploaderType
 */
export type UploaderType = 'admin' | 'user' | 'system';

/**
 * UserAuthSessionOut
 */
export type UserAuthSessionOut = {
    /**
     * 当前认证主体信息
     */
    principal: UserPrincipalOut;
    /**
     * Session Id
     *
     * 登录会话唯一标识
     */
    session_id: string;
    /**
     * Access Expires At
     *
     * 访问凭据过期时间
     */
    access_expires_at: string;
    /**
     * Idle Expires At
     *
     * 会话空闲过期时间
     */
    idle_expires_at: string;
    /**
     * Absolute Expires At
     *
     * 会话绝对过期时间
     */
    absolute_expires_at: string;
};

/**
 * UserLoginIn
 */
export type UserLoginIn = {
    /**
     * Username
     *
     * 登录用户名
     */
    username: string;
    /**
     * Password
     *
     * 登录密码，最多 64 个字符
     */
    password: string;
};

/**
 * UserPrincipalOut
 */
export type UserPrincipalOut = {
    /**
     * Id
     *
     * 资源唯一标识
     */
    id: string;
    /**
     * Username
     *
     * 登录用户名
     */
    username: string;
    /**
     * Display Name
     *
     * 展示名称
     */
    display_name: string | null;
    /**
     * Email
     *
     * 电子邮箱地址
     */
    email: string | null;
    /**
     * Is Active
     *
     * 资源当前是否启用
     */
    is_active: boolean;
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string;
    /**
     * Updated At
     *
     * 最近更新时间
     */
    updated_at: string;
};

/**
 * UserRegisterIn
 */
export type UserRegisterIn = {
    /**
     * Username
     *
     * 登录用户名
     */
    username: string;
    /**
     * Password
     *
     * 登录密码，长度为 6 至 64 个字符
     */
    password: string;
    /**
     * Display Name
     *
     * 展示名称
     */
    display_name?: string | null;
    /**
     * Email
     *
     * 电子邮箱地址
     */
    email?: string | null;
};

/**
 * UserUpdateIn
 */
export type UserUpdateIn = {
    /**
     * Display Name
     *
     * 展示名称
     */
    display_name?: string | null;
    /**
     * Email
     *
     * 电子邮箱地址
     */
    email?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     *
     * 错误字段在请求中的位置
     */
    loc: Array<string | number>;
    /**
     * Message
     *
     * 参数校验错误消息
     */
    msg: string;
    /**
     * Error Type
     *
     * 参数校验错误类型
     */
    type: string;
    /**
     * Input
     *
     * 引发校验错误的输入值，敏感内容可能被省略
     */
    input?: unknown;
    /**
     * Context
     *
     * 参数校验错误的补充上下文
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type RegisterApiV1AuthRegisterPostData = {
    body: UserRegisterIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterApiV1AuthRegisterPostErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type RegisterApiV1AuthRegisterPostError = RegisterApiV1AuthRegisterPostErrors[keyof RegisterApiV1AuthRegisterPostErrors];

export type RegisterApiV1AuthRegisterPostResponses = {
    /**
     * 请求成功
     */
    201: ResponseModelUserAuthSessionOut;
};

export type RegisterApiV1AuthRegisterPostResponse = RegisterApiV1AuthRegisterPostResponses[keyof RegisterApiV1AuthRegisterPostResponses];

export type LoginApiV1AuthLoginPostData = {
    body: UserLoginIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelUserAuthSessionOut;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type RefreshApiV1AuthRefreshPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshApiV1AuthRefreshPostErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type RefreshApiV1AuthRefreshPostError = RefreshApiV1AuthRefreshPostErrors[keyof RefreshApiV1AuthRefreshPostErrors];

export type RefreshApiV1AuthRefreshPostResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelRefreshSessionOut;
};

export type RefreshApiV1AuthRefreshPostResponse = RefreshApiV1AuthRefreshPostResponses[keyof RefreshApiV1AuthRefreshPostResponses];

export type LogoutApiV1AuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type LogoutApiV1AuthLogoutPostError = LogoutApiV1AuthLogoutPostErrors[keyof LogoutApiV1AuthLogoutPostErrors];

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelBool;
};

export type LogoutApiV1AuthLogoutPostResponse = LogoutApiV1AuthLogoutPostResponses[keyof LogoutApiV1AuthLogoutPostResponses];

export type UploadAssetApiV1AssetsUploadPostData = {
    body: BodyUploadAssetApiV1AssetsUploadPost;
    path?: never;
    query?: never;
    url: '/api/v1/assets/upload';
};

export type UploadAssetApiV1AssetsUploadPostErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type UploadAssetApiV1AssetsUploadPostError = UploadAssetApiV1AssetsUploadPostErrors[keyof UploadAssetApiV1AssetsUploadPostErrors];

export type UploadAssetApiV1AssetsUploadPostResponses = {
    /**
     * 请求成功
     */
    201: ResponseModelAssetRead;
};

export type UploadAssetApiV1AssetsUploadPostResponse = UploadAssetApiV1AssetsUploadPostResponses[keyof UploadAssetApiV1AssetsUploadPostResponses];

export type ListAssetsApiV1AssetsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/assets';
};

export type ListAssetsApiV1AssetsGetErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type ListAssetsApiV1AssetsGetError = ListAssetsApiV1AssetsGetErrors[keyof ListAssetsApiV1AssetsGetErrors];

export type ListAssetsApiV1AssetsGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelPageResultAssetRead;
};

export type ListAssetsApiV1AssetsGetResponse = ListAssetsApiV1AssetsGetResponses[keyof ListAssetsApiV1AssetsGetResponses];

export type DeleteAssetApiV1AssetsAssetIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Confirmation
         */
        'X-Admin-Confirmation'?: string | null;
    };
    path: {
        /**
         * Asset Id
         */
        asset_id: string;
    };
    query?: never;
    url: '/api/v1/assets/{asset_id}';
};

export type DeleteAssetApiV1AssetsAssetIdDeleteErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type DeleteAssetApiV1AssetsAssetIdDeleteError = DeleteAssetApiV1AssetsAssetIdDeleteErrors[keyof DeleteAssetApiV1AssetsAssetIdDeleteErrors];

export type DeleteAssetApiV1AssetsAssetIdDeleteResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelBool;
};

export type DeleteAssetApiV1AssetsAssetIdDeleteResponse = DeleteAssetApiV1AssetsAssetIdDeleteResponses[keyof DeleteAssetApiV1AssetsAssetIdDeleteResponses];

export type DeleteAccountApiV1UsersMeDeleteData = {
    body: AccountDeleteIn;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type DeleteAccountApiV1UsersMeDeleteErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type DeleteAccountApiV1UsersMeDeleteError = DeleteAccountApiV1UsersMeDeleteErrors[keyof DeleteAccountApiV1UsersMeDeleteErrors];

export type DeleteAccountApiV1UsersMeDeleteResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelActionResult;
};

export type DeleteAccountApiV1UsersMeDeleteResponse = DeleteAccountApiV1UsersMeDeleteResponses[keyof DeleteAccountApiV1UsersMeDeleteResponses];

export type GetMeApiV1UsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetMeApiV1UsersMeGetErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type GetMeApiV1UsersMeGetError = GetMeApiV1UsersMeGetErrors[keyof GetMeApiV1UsersMeGetErrors];

export type GetMeApiV1UsersMeGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelUserPrincipalOut;
};

export type GetMeApiV1UsersMeGetResponse = GetMeApiV1UsersMeGetResponses[keyof GetMeApiV1UsersMeGetResponses];

export type UpdateMeApiV1UsersMePatchData = {
    body: UserUpdateIn;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateMeApiV1UsersMePatchErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type UpdateMeApiV1UsersMePatchError = UpdateMeApiV1UsersMePatchErrors[keyof UpdateMeApiV1UsersMePatchErrors];

export type UpdateMeApiV1UsersMePatchResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelUserPrincipalOut;
};

export type UpdateMeApiV1UsersMePatchResponse = UpdateMeApiV1UsersMePatchResponses[keyof UpdateMeApiV1UsersMePatchResponses];

export type ChangePasswordApiV1UsersMePasswordPostData = {
    body: PasswordChangeIn;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type ChangePasswordApiV1UsersMePasswordPostErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type ChangePasswordApiV1UsersMePasswordPostError = ChangePasswordApiV1UsersMePasswordPostErrors[keyof ChangePasswordApiV1UsersMePasswordPostErrors];

export type ChangePasswordApiV1UsersMePasswordPostResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelRefreshSessionOut;
};

export type ChangePasswordApiV1UsersMePasswordPostResponse = ChangePasswordApiV1UsersMePasswordPostResponses[keyof ChangePasswordApiV1UsersMePasswordPostResponses];

export type ListSessionsApiV1UsersMeSessionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/users/me/sessions';
};

export type ListSessionsApiV1UsersMeSessionsGetErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type ListSessionsApiV1UsersMeSessionsGetError = ListSessionsApiV1UsersMeSessionsGetErrors[keyof ListSessionsApiV1UsersMeSessionsGetErrors];

export type ListSessionsApiV1UsersMeSessionsGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelPageResultSessionRead;
};

export type ListSessionsApiV1UsersMeSessionsGetResponse = ListSessionsApiV1UsersMeSessionsGetResponses[keyof ListSessionsApiV1UsersMeSessionsGetResponses];

export type RevokeSessionApiV1UsersMeSessionsSessionIdDeleteData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/users/me/sessions/{session_id}';
};

export type RevokeSessionApiV1UsersMeSessionsSessionIdDeleteErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type RevokeSessionApiV1UsersMeSessionsSessionIdDeleteError = RevokeSessionApiV1UsersMeSessionsSessionIdDeleteErrors[keyof RevokeSessionApiV1UsersMeSessionsSessionIdDeleteErrors];

export type RevokeSessionApiV1UsersMeSessionsSessionIdDeleteResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelActionResult;
};

export type RevokeSessionApiV1UsersMeSessionsSessionIdDeleteResponse = RevokeSessionApiV1UsersMeSessionsSessionIdDeleteResponses[keyof RevokeSessionApiV1UsersMeSessionsSessionIdDeleteResponses];

export type RevokeOtherSessionsApiV1UsersMeSessionsRevokeOthersPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/sessions/revoke-others';
};

export type RevokeOtherSessionsApiV1UsersMeSessionsRevokeOthersPostErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type RevokeOtherSessionsApiV1UsersMeSessionsRevokeOthersPostError = RevokeOtherSessionsApiV1UsersMeSessionsRevokeOthersPostErrors[keyof RevokeOtherSessionsApiV1UsersMeSessionsRevokeOthersPostErrors];

export type RevokeOtherSessionsApiV1UsersMeSessionsRevokeOthersPostResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelActionResult;
};

export type RevokeOtherSessionsApiV1UsersMeSessionsRevokeOthersPostResponse = RevokeOtherSessionsApiV1UsersMeSessionsRevokeOthersPostResponses[keyof RevokeOtherSessionsApiV1UsersMeSessionsRevokeOthersPostResponses];

export type LoginApiV1AdminAuthLoginPostData = {
    body: AdminLoginIn;
    path?: never;
    query?: never;
    url: '/api/v1/admin/auth/login';
};

export type LoginApiV1AdminAuthLoginPostErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type LoginApiV1AdminAuthLoginPostError = LoginApiV1AdminAuthLoginPostErrors[keyof LoginApiV1AdminAuthLoginPostErrors];

export type LoginApiV1AdminAuthLoginPostResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelAdminAuthSessionOut;
};

export type LoginApiV1AdminAuthLoginPostResponse = LoginApiV1AdminAuthLoginPostResponses[keyof LoginApiV1AdminAuthLoginPostResponses];

export type RefreshApiV1AdminAuthRefreshPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/auth/refresh';
};

export type RefreshApiV1AdminAuthRefreshPostErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type RefreshApiV1AdminAuthRefreshPostError = RefreshApiV1AdminAuthRefreshPostErrors[keyof RefreshApiV1AdminAuthRefreshPostErrors];

export type RefreshApiV1AdminAuthRefreshPostResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelRefreshSessionOut;
};

export type RefreshApiV1AdminAuthRefreshPostResponse = RefreshApiV1AdminAuthRefreshPostResponses[keyof RefreshApiV1AdminAuthRefreshPostResponses];

export type LogoutApiV1AdminAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/auth/logout';
};

export type LogoutApiV1AdminAuthLogoutPostErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type LogoutApiV1AdminAuthLogoutPostError = LogoutApiV1AdminAuthLogoutPostErrors[keyof LogoutApiV1AdminAuthLogoutPostErrors];

export type LogoutApiV1AdminAuthLogoutPostResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelBool;
};

export type LogoutApiV1AdminAuthLogoutPostResponse = LogoutApiV1AdminAuthLogoutPostResponses[keyof LogoutApiV1AdminAuthLogoutPostResponses];

export type GetMeApiV1AdminAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/auth/me';
};

export type GetMeApiV1AdminAuthMeGetErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type GetMeApiV1AdminAuthMeGetError = GetMeApiV1AdminAuthMeGetErrors[keyof GetMeApiV1AdminAuthMeGetErrors];

export type GetMeApiV1AdminAuthMeGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelAdminRead;
};

export type GetMeApiV1AdminAuthMeGetResponse = GetMeApiV1AdminAuthMeGetResponses[keyof GetMeApiV1AdminAuthMeGetResponses];

export type UpdateProfileApiV1AdminAuthProfilePatchData = {
    body: AdminProfileUpdateIn;
    path?: never;
    query?: never;
    url: '/api/v1/admin/auth/profile';
};

export type UpdateProfileApiV1AdminAuthProfilePatchErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type UpdateProfileApiV1AdminAuthProfilePatchError = UpdateProfileApiV1AdminAuthProfilePatchErrors[keyof UpdateProfileApiV1AdminAuthProfilePatchErrors];

export type UpdateProfileApiV1AdminAuthProfilePatchResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelAdminRead;
};

export type UpdateProfileApiV1AdminAuthProfilePatchResponse = UpdateProfileApiV1AdminAuthProfilePatchResponses[keyof UpdateProfileApiV1AdminAuthProfilePatchResponses];

export type ChangePasswordApiV1AdminAuthPasswordPostData = {
    body: PasswordChangeIn;
    path?: never;
    query?: never;
    url: '/api/v1/admin/auth/password';
};

export type ChangePasswordApiV1AdminAuthPasswordPostErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type ChangePasswordApiV1AdminAuthPasswordPostError = ChangePasswordApiV1AdminAuthPasswordPostErrors[keyof ChangePasswordApiV1AdminAuthPasswordPostErrors];

export type ChangePasswordApiV1AdminAuthPasswordPostResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelRefreshSessionOut;
};

export type ChangePasswordApiV1AdminAuthPasswordPostResponse = ChangePasswordApiV1AdminAuthPasswordPostResponses[keyof ChangePasswordApiV1AdminAuthPasswordPostResponses];

export type ConfirmApiV1AdminAuthConfirmPostData = {
    body: AdminConfirmIn;
    path?: never;
    query?: never;
    url: '/api/v1/admin/auth/confirm';
};

export type ConfirmApiV1AdminAuthConfirmPostErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type ConfirmApiV1AdminAuthConfirmPostError = ConfirmApiV1AdminAuthConfirmPostErrors[keyof ConfirmApiV1AdminAuthConfirmPostErrors];

export type ConfirmApiV1AdminAuthConfirmPostResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelAdminConfirmOut;
};

export type ConfirmApiV1AdminAuthConfirmPostResponse = ConfirmApiV1AdminAuthConfirmPostResponses[keyof ConfirmApiV1AdminAuthConfirmPostResponses];

export type ListUsersApiV1AdminUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/api/v1/admin/users';
};

export type ListUsersApiV1AdminUsersGetErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type ListUsersApiV1AdminUsersGetError = ListUsersApiV1AdminUsersGetErrors[keyof ListUsersApiV1AdminUsersGetErrors];

export type ListUsersApiV1AdminUsersGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelPageResultUserPrincipalOut;
};

export type ListUsersApiV1AdminUsersGetResponse = ListUsersApiV1AdminUsersGetResponses[keyof ListUsersApiV1AdminUsersGetResponses];

export type GetUserApiV1AdminUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}';
};

export type GetUserApiV1AdminUsersUserIdGetErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type GetUserApiV1AdminUsersUserIdGetError = GetUserApiV1AdminUsersUserIdGetErrors[keyof GetUserApiV1AdminUsersUserIdGetErrors];

export type GetUserApiV1AdminUsersUserIdGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelUserPrincipalOut;
};

export type GetUserApiV1AdminUsersUserIdGetResponse = GetUserApiV1AdminUsersUserIdGetResponses[keyof GetUserApiV1AdminUsersUserIdGetResponses];

export type UpdateUserApiV1AdminUsersUserIdPatchData = {
    body: UserUpdateIn;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}';
};

export type UpdateUserApiV1AdminUsersUserIdPatchErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type UpdateUserApiV1AdminUsersUserIdPatchError = UpdateUserApiV1AdminUsersUserIdPatchErrors[keyof UpdateUserApiV1AdminUsersUserIdPatchErrors];

export type UpdateUserApiV1AdminUsersUserIdPatchResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelUserPrincipalOut;
};

export type UpdateUserApiV1AdminUsersUserIdPatchResponse = UpdateUserApiV1AdminUsersUserIdPatchResponses[keyof UpdateUserApiV1AdminUsersUserIdPatchResponses];

export type SetUserStatusApiV1AdminUsersUserIdStatusPatchData = {
    body: StatusUpdateIn;
    headers?: {
        /**
         * X-Admin-Confirmation
         */
        'X-Admin-Confirmation'?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/status';
};

export type SetUserStatusApiV1AdminUsersUserIdStatusPatchErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type SetUserStatusApiV1AdminUsersUserIdStatusPatchError = SetUserStatusApiV1AdminUsersUserIdStatusPatchErrors[keyof SetUserStatusApiV1AdminUsersUserIdStatusPatchErrors];

export type SetUserStatusApiV1AdminUsersUserIdStatusPatchResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelUserPrincipalOut;
};

export type SetUserStatusApiV1AdminUsersUserIdStatusPatchResponse = SetUserStatusApiV1AdminUsersUserIdStatusPatchResponses[keyof SetUserStatusApiV1AdminUsersUserIdStatusPatchResponses];

export type ResetUserPasswordApiV1AdminUsersUserIdCredentialsPasswordPutData = {
    body: PasswordResetIn;
    headers?: {
        /**
         * X-Admin-Confirmation
         */
        'X-Admin-Confirmation'?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/credentials/password';
};

export type ResetUserPasswordApiV1AdminUsersUserIdCredentialsPasswordPutErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type ResetUserPasswordApiV1AdminUsersUserIdCredentialsPasswordPutError = ResetUserPasswordApiV1AdminUsersUserIdCredentialsPasswordPutErrors[keyof ResetUserPasswordApiV1AdminUsersUserIdCredentialsPasswordPutErrors];

export type ResetUserPasswordApiV1AdminUsersUserIdCredentialsPasswordPutResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelActionResult;
};

export type ResetUserPasswordApiV1AdminUsersUserIdCredentialsPasswordPutResponse = ResetUserPasswordApiV1AdminUsersUserIdCredentialsPasswordPutResponses[keyof ResetUserPasswordApiV1AdminUsersUserIdCredentialsPasswordPutResponses];

export type ListUserSessionsApiV1AdminUsersUserIdSessionsGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/admin/users/{user_id}/sessions';
};

export type ListUserSessionsApiV1AdminUsersUserIdSessionsGetErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type ListUserSessionsApiV1AdminUsersUserIdSessionsGetError = ListUserSessionsApiV1AdminUsersUserIdSessionsGetErrors[keyof ListUserSessionsApiV1AdminUsersUserIdSessionsGetErrors];

export type ListUserSessionsApiV1AdminUsersUserIdSessionsGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelPageResultSessionRead;
};

export type ListUserSessionsApiV1AdminUsersUserIdSessionsGetResponse = ListUserSessionsApiV1AdminUsersUserIdSessionsGetResponses[keyof ListUserSessionsApiV1AdminUsersUserIdSessionsGetResponses];

export type RevokeUserSessionApiV1AdminUsersUserIdSessionsSessionIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Confirmation
         */
        'X-Admin-Confirmation'?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/sessions/{session_id}';
};

export type RevokeUserSessionApiV1AdminUsersUserIdSessionsSessionIdDeleteErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type RevokeUserSessionApiV1AdminUsersUserIdSessionsSessionIdDeleteError = RevokeUserSessionApiV1AdminUsersUserIdSessionsSessionIdDeleteErrors[keyof RevokeUserSessionApiV1AdminUsersUserIdSessionsSessionIdDeleteErrors];

export type RevokeUserSessionApiV1AdminUsersUserIdSessionsSessionIdDeleteResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelActionResult;
};

export type RevokeUserSessionApiV1AdminUsersUserIdSessionsSessionIdDeleteResponse = RevokeUserSessionApiV1AdminUsersUserIdSessionsSessionIdDeleteResponses[keyof RevokeUserSessionApiV1AdminUsersUserIdSessionsSessionIdDeleteResponses];

export type RevokeAllUserSessionsApiV1AdminUsersUserIdSessionsRevokeAllPostData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Confirmation
         */
        'X-Admin-Confirmation'?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/sessions/revoke-all';
};

export type RevokeAllUserSessionsApiV1AdminUsersUserIdSessionsRevokeAllPostErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type RevokeAllUserSessionsApiV1AdminUsersUserIdSessionsRevokeAllPostError = RevokeAllUserSessionsApiV1AdminUsersUserIdSessionsRevokeAllPostErrors[keyof RevokeAllUserSessionsApiV1AdminUsersUserIdSessionsRevokeAllPostErrors];

export type RevokeAllUserSessionsApiV1AdminUsersUserIdSessionsRevokeAllPostResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelActionResult;
};

export type RevokeAllUserSessionsApiV1AdminUsersUserIdSessionsRevokeAllPostResponse = RevokeAllUserSessionsApiV1AdminUsersUserIdSessionsRevokeAllPostResponses[keyof RevokeAllUserSessionsApiV1AdminUsersUserIdSessionsRevokeAllPostResponses];

export type ListAdminsApiV1AdminAdminsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/admin/admins';
};

export type ListAdminsApiV1AdminAdminsGetErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type ListAdminsApiV1AdminAdminsGetError = ListAdminsApiV1AdminAdminsGetErrors[keyof ListAdminsApiV1AdminAdminsGetErrors];

export type ListAdminsApiV1AdminAdminsGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelPageResultAdminRead;
};

export type ListAdminsApiV1AdminAdminsGetResponse = ListAdminsApiV1AdminAdminsGetResponses[keyof ListAdminsApiV1AdminAdminsGetResponses];

export type CreateAdminApiV1AdminAdminsPostData = {
    body: AdminCreateIn;
    headers?: {
        /**
         * X-Admin-Confirmation
         */
        'X-Admin-Confirmation'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/admins';
};

export type CreateAdminApiV1AdminAdminsPostErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type CreateAdminApiV1AdminAdminsPostError = CreateAdminApiV1AdminAdminsPostErrors[keyof CreateAdminApiV1AdminAdminsPostErrors];

export type CreateAdminApiV1AdminAdminsPostResponses = {
    /**
     * 请求成功
     */
    201: ResponseModelAdminRead;
};

export type CreateAdminApiV1AdminAdminsPostResponse = CreateAdminApiV1AdminAdminsPostResponses[keyof CreateAdminApiV1AdminAdminsPostResponses];

export type SetAdminStatusBulkApiV1AdminAdminsStatusBatchPatchData = {
    body: AdminBulkStatusUpdateIn;
    headers?: {
        /**
         * X-Admin-Confirmation
         */
        'X-Admin-Confirmation'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/admins/status/batch';
};

export type SetAdminStatusBulkApiV1AdminAdminsStatusBatchPatchErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type SetAdminStatusBulkApiV1AdminAdminsStatusBatchPatchError = SetAdminStatusBulkApiV1AdminAdminsStatusBatchPatchErrors[keyof SetAdminStatusBulkApiV1AdminAdminsStatusBatchPatchErrors];

export type SetAdminStatusBulkApiV1AdminAdminsStatusBatchPatchResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelListAdminRead;
};

export type SetAdminStatusBulkApiV1AdminAdminsStatusBatchPatchResponse = SetAdminStatusBulkApiV1AdminAdminsStatusBatchPatchResponses[keyof SetAdminStatusBulkApiV1AdminAdminsStatusBatchPatchResponses];

export type GetAdminApiV1AdminAdminsAdminIdGetData = {
    body?: never;
    path: {
        /**
         * Admin Id
         */
        admin_id: string;
    };
    query?: never;
    url: '/api/v1/admin/admins/{admin_id}';
};

export type GetAdminApiV1AdminAdminsAdminIdGetErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type GetAdminApiV1AdminAdminsAdminIdGetError = GetAdminApiV1AdminAdminsAdminIdGetErrors[keyof GetAdminApiV1AdminAdminsAdminIdGetErrors];

export type GetAdminApiV1AdminAdminsAdminIdGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelAdminRead;
};

export type GetAdminApiV1AdminAdminsAdminIdGetResponse = GetAdminApiV1AdminAdminsAdminIdGetResponses[keyof GetAdminApiV1AdminAdminsAdminIdGetResponses];

export type UpdateAdminApiV1AdminAdminsAdminIdPatchData = {
    body: AdminUpdateIn;
    headers?: {
        /**
         * X-Admin-Confirmation
         */
        'X-Admin-Confirmation'?: string | null;
    };
    path: {
        /**
         * Admin Id
         */
        admin_id: string;
    };
    query?: never;
    url: '/api/v1/admin/admins/{admin_id}';
};

export type UpdateAdminApiV1AdminAdminsAdminIdPatchErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type UpdateAdminApiV1AdminAdminsAdminIdPatchError = UpdateAdminApiV1AdminAdminsAdminIdPatchErrors[keyof UpdateAdminApiV1AdminAdminsAdminIdPatchErrors];

export type UpdateAdminApiV1AdminAdminsAdminIdPatchResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelAdminRead;
};

export type UpdateAdminApiV1AdminAdminsAdminIdPatchResponse = UpdateAdminApiV1AdminAdminsAdminIdPatchResponses[keyof UpdateAdminApiV1AdminAdminsAdminIdPatchResponses];

export type SetAdminStatusApiV1AdminAdminsAdminIdStatusPatchData = {
    body: StatusUpdateIn;
    headers?: {
        /**
         * X-Admin-Confirmation
         */
        'X-Admin-Confirmation'?: string | null;
    };
    path: {
        /**
         * Admin Id
         */
        admin_id: string;
    };
    query?: never;
    url: '/api/v1/admin/admins/{admin_id}/status';
};

export type SetAdminStatusApiV1AdminAdminsAdminIdStatusPatchErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type SetAdminStatusApiV1AdminAdminsAdminIdStatusPatchError = SetAdminStatusApiV1AdminAdminsAdminIdStatusPatchErrors[keyof SetAdminStatusApiV1AdminAdminsAdminIdStatusPatchErrors];

export type SetAdminStatusApiV1AdminAdminsAdminIdStatusPatchResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelAdminRead;
};

export type SetAdminStatusApiV1AdminAdminsAdminIdStatusPatchResponse = SetAdminStatusApiV1AdminAdminsAdminIdStatusPatchResponses[keyof SetAdminStatusApiV1AdminAdminsAdminIdStatusPatchResponses];

export type ResetAdminPasswordApiV1AdminAdminsAdminIdCredentialsPasswordPutData = {
    body: PasswordResetIn;
    headers?: {
        /**
         * X-Admin-Confirmation
         */
        'X-Admin-Confirmation'?: string | null;
    };
    path: {
        /**
         * Admin Id
         */
        admin_id: string;
    };
    query?: never;
    url: '/api/v1/admin/admins/{admin_id}/credentials/password';
};

export type ResetAdminPasswordApiV1AdminAdminsAdminIdCredentialsPasswordPutErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type ResetAdminPasswordApiV1AdminAdminsAdminIdCredentialsPasswordPutError = ResetAdminPasswordApiV1AdminAdminsAdminIdCredentialsPasswordPutErrors[keyof ResetAdminPasswordApiV1AdminAdminsAdminIdCredentialsPasswordPutErrors];

export type ResetAdminPasswordApiV1AdminAdminsAdminIdCredentialsPasswordPutResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelActionResult;
};

export type ResetAdminPasswordApiV1AdminAdminsAdminIdCredentialsPasswordPutResponse = ResetAdminPasswordApiV1AdminAdminsAdminIdCredentialsPasswordPutResponses[keyof ResetAdminPasswordApiV1AdminAdminsAdminIdCredentialsPasswordPutResponses];

export type AssignAdminRolesApiV1AdminAdminsAdminIdRolesPutData = {
    body: AdminRoleAssignIn;
    headers?: {
        /**
         * X-Admin-Confirmation
         */
        'X-Admin-Confirmation'?: string | null;
    };
    path: {
        /**
         * Admin Id
         */
        admin_id: string;
    };
    query?: never;
    url: '/api/v1/admin/admins/{admin_id}/roles';
};

export type AssignAdminRolesApiV1AdminAdminsAdminIdRolesPutErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type AssignAdminRolesApiV1AdminAdminsAdminIdRolesPutError = AssignAdminRolesApiV1AdminAdminsAdminIdRolesPutErrors[keyof AssignAdminRolesApiV1AdminAdminsAdminIdRolesPutErrors];

export type AssignAdminRolesApiV1AdminAdminsAdminIdRolesPutResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelAdminRead;
};

export type AssignAdminRolesApiV1AdminAdminsAdminIdRolesPutResponse = AssignAdminRolesApiV1AdminAdminsAdminIdRolesPutResponses[keyof AssignAdminRolesApiV1AdminAdminsAdminIdRolesPutResponses];

export type ListAdminSessionsApiV1AdminAdminsAdminIdSessionsGetData = {
    body?: never;
    path: {
        /**
         * Admin Id
         */
        admin_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/admin/admins/{admin_id}/sessions';
};

export type ListAdminSessionsApiV1AdminAdminsAdminIdSessionsGetErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type ListAdminSessionsApiV1AdminAdminsAdminIdSessionsGetError = ListAdminSessionsApiV1AdminAdminsAdminIdSessionsGetErrors[keyof ListAdminSessionsApiV1AdminAdminsAdminIdSessionsGetErrors];

export type ListAdminSessionsApiV1AdminAdminsAdminIdSessionsGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelPageResultSessionRead;
};

export type ListAdminSessionsApiV1AdminAdminsAdminIdSessionsGetResponse = ListAdminSessionsApiV1AdminAdminsAdminIdSessionsGetResponses[keyof ListAdminSessionsApiV1AdminAdminsAdminIdSessionsGetResponses];

export type RevokeAllAdminSessionsApiV1AdminAdminsAdminIdSessionsRevokeAllPostData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Confirmation
         */
        'X-Admin-Confirmation'?: string | null;
    };
    path: {
        /**
         * Admin Id
         */
        admin_id: string;
    };
    query?: never;
    url: '/api/v1/admin/admins/{admin_id}/sessions/revoke-all';
};

export type RevokeAllAdminSessionsApiV1AdminAdminsAdminIdSessionsRevokeAllPostErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type RevokeAllAdminSessionsApiV1AdminAdminsAdminIdSessionsRevokeAllPostError = RevokeAllAdminSessionsApiV1AdminAdminsAdminIdSessionsRevokeAllPostErrors[keyof RevokeAllAdminSessionsApiV1AdminAdminsAdminIdSessionsRevokeAllPostErrors];

export type RevokeAllAdminSessionsApiV1AdminAdminsAdminIdSessionsRevokeAllPostResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelActionResult;
};

export type RevokeAllAdminSessionsApiV1AdminAdminsAdminIdSessionsRevokeAllPostResponse = RevokeAllAdminSessionsApiV1AdminAdminsAdminIdSessionsRevokeAllPostResponses[keyof RevokeAllAdminSessionsApiV1AdminAdminsAdminIdSessionsRevokeAllPostResponses];

export type ListRolesApiV1AdminRolesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/admin/roles';
};

export type ListRolesApiV1AdminRolesGetErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type ListRolesApiV1AdminRolesGetError = ListRolesApiV1AdminRolesGetErrors[keyof ListRolesApiV1AdminRolesGetErrors];

export type ListRolesApiV1AdminRolesGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelPageResultRoleRead;
};

export type ListRolesApiV1AdminRolesGetResponse = ListRolesApiV1AdminRolesGetResponses[keyof ListRolesApiV1AdminRolesGetResponses];

export type CreateRoleApiV1AdminRolesPostData = {
    body: RoleCreateIn;
    path?: never;
    query?: never;
    url: '/api/v1/admin/roles';
};

export type CreateRoleApiV1AdminRolesPostErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type CreateRoleApiV1AdminRolesPostError = CreateRoleApiV1AdminRolesPostErrors[keyof CreateRoleApiV1AdminRolesPostErrors];

export type CreateRoleApiV1AdminRolesPostResponses = {
    /**
     * 请求成功
     */
    201: ResponseModelRoleRead;
};

export type CreateRoleApiV1AdminRolesPostResponse = CreateRoleApiV1AdminRolesPostResponses[keyof CreateRoleApiV1AdminRolesPostResponses];

export type DeleteRoleApiV1AdminRolesRoleIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Confirmation
         */
        'X-Admin-Confirmation'?: string | null;
    };
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/admin/roles/{role_id}';
};

export type DeleteRoleApiV1AdminRolesRoleIdDeleteErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type DeleteRoleApiV1AdminRolesRoleIdDeleteError = DeleteRoleApiV1AdminRolesRoleIdDeleteErrors[keyof DeleteRoleApiV1AdminRolesRoleIdDeleteErrors];

export type DeleteRoleApiV1AdminRolesRoleIdDeleteResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelActionResult;
};

export type DeleteRoleApiV1AdminRolesRoleIdDeleteResponse = DeleteRoleApiV1AdminRolesRoleIdDeleteResponses[keyof DeleteRoleApiV1AdminRolesRoleIdDeleteResponses];

export type GetRoleApiV1AdminRolesRoleIdGetData = {
    body?: never;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/admin/roles/{role_id}';
};

export type GetRoleApiV1AdminRolesRoleIdGetErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type GetRoleApiV1AdminRolesRoleIdGetError = GetRoleApiV1AdminRolesRoleIdGetErrors[keyof GetRoleApiV1AdminRolesRoleIdGetErrors];

export type GetRoleApiV1AdminRolesRoleIdGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelRoleRead;
};

export type GetRoleApiV1AdminRolesRoleIdGetResponse = GetRoleApiV1AdminRolesRoleIdGetResponses[keyof GetRoleApiV1AdminRolesRoleIdGetResponses];

export type UpdateRoleApiV1AdminRolesRoleIdPatchData = {
    body: RoleUpdateIn;
    headers?: {
        /**
         * X-Admin-Confirmation
         */
        'X-Admin-Confirmation'?: string | null;
    };
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/admin/roles/{role_id}';
};

export type UpdateRoleApiV1AdminRolesRoleIdPatchErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type UpdateRoleApiV1AdminRolesRoleIdPatchError = UpdateRoleApiV1AdminRolesRoleIdPatchErrors[keyof UpdateRoleApiV1AdminRolesRoleIdPatchErrors];

export type UpdateRoleApiV1AdminRolesRoleIdPatchResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelRoleRead;
};

export type UpdateRoleApiV1AdminRolesRoleIdPatchResponse = UpdateRoleApiV1AdminRolesRoleIdPatchResponses[keyof UpdateRoleApiV1AdminRolesRoleIdPatchResponses];

export type AssignRolePermissionsApiV1AdminRolesRoleIdPermissionsPutData = {
    body: RolePermissionAssignIn;
    headers?: {
        /**
         * X-Admin-Confirmation
         */
        'X-Admin-Confirmation'?: string | null;
    };
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/admin/roles/{role_id}/permissions';
};

export type AssignRolePermissionsApiV1AdminRolesRoleIdPermissionsPutErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type AssignRolePermissionsApiV1AdminRolesRoleIdPermissionsPutError = AssignRolePermissionsApiV1AdminRolesRoleIdPermissionsPutErrors[keyof AssignRolePermissionsApiV1AdminRolesRoleIdPermissionsPutErrors];

export type AssignRolePermissionsApiV1AdminRolesRoleIdPermissionsPutResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelRoleRead;
};

export type AssignRolePermissionsApiV1AdminRolesRoleIdPermissionsPutResponse = AssignRolePermissionsApiV1AdminRolesRoleIdPermissionsPutResponses[keyof AssignRolePermissionsApiV1AdminRolesRoleIdPermissionsPutResponses];

export type ListPermissionsApiV1AdminPermissionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/permissions';
};

export type ListPermissionsApiV1AdminPermissionsGetErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type ListPermissionsApiV1AdminPermissionsGetError = ListPermissionsApiV1AdminPermissionsGetErrors[keyof ListPermissionsApiV1AdminPermissionsGetErrors];

export type ListPermissionsApiV1AdminPermissionsGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelListPermissionRead;
};

export type ListPermissionsApiV1AdminPermissionsGetResponse = ListPermissionsApiV1AdminPermissionsGetResponses[keyof ListPermissionsApiV1AdminPermissionsGetResponses];

export type ListLoginEventsApiV1AdminSecurityLoginEventsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/admin/security/login-events';
};

export type ListLoginEventsApiV1AdminSecurityLoginEventsGetErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type ListLoginEventsApiV1AdminSecurityLoginEventsGetError = ListLoginEventsApiV1AdminSecurityLoginEventsGetErrors[keyof ListLoginEventsApiV1AdminSecurityLoginEventsGetErrors];

export type ListLoginEventsApiV1AdminSecurityLoginEventsGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelPageResultLoginEventRead;
};

export type ListLoginEventsApiV1AdminSecurityLoginEventsGetResponse = ListLoginEventsApiV1AdminSecurityLoginEventsGetResponses[keyof ListLoginEventsApiV1AdminSecurityLoginEventsGetResponses];

export type ListAuditEventsApiV1AdminSecurityAuditEventsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/admin/security/audit-events';
};

export type ListAuditEventsApiV1AdminSecurityAuditEventsGetErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type ListAuditEventsApiV1AdminSecurityAuditEventsGetError = ListAuditEventsApiV1AdminSecurityAuditEventsGetErrors[keyof ListAuditEventsApiV1AdminSecurityAuditEventsGetErrors];

export type ListAuditEventsApiV1AdminSecurityAuditEventsGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelPageResultAuditEventRead;
};

export type ListAuditEventsApiV1AdminSecurityAuditEventsGetResponse = ListAuditEventsApiV1AdminSecurityAuditEventsGetResponses[keyof ListAuditEventsApiV1AdminSecurityAuditEventsGetResponses];

export type ListRequestLogsApiV1AdminSystemRequestLogsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/admin/system/request-logs';
};

export type ListRequestLogsApiV1AdminSystemRequestLogsGetErrors = {
    /**
     * 请求参数校验失败
     */
    422: HttpValidationError;
};

export type ListRequestLogsApiV1AdminSystemRequestLogsGetError = ListRequestLogsApiV1AdminSystemRequestLogsGetErrors[keyof ListRequestLogsApiV1AdminSystemRequestLogsGetErrors];

export type ListRequestLogsApiV1AdminSystemRequestLogsGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelPageResultRequestLogRead;
};

export type ListRequestLogsApiV1AdminSystemRequestLogsGetResponse = ListRequestLogsApiV1AdminSystemRequestLogsGetResponses[keyof ListRequestLogsApiV1AdminSystemRequestLogsGetResponses];

export type GetSystemStatusApiV1SystemStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/status';
};

export type GetSystemStatusApiV1SystemStatusGetResponses = {
    /**
     * 请求成功
     */
    200: ResponseModelSystemStatus;
};

export type GetSystemStatusApiV1SystemStatusGetResponse = GetSystemStatusApiV1SystemStatusGetResponses[keyof GetSystemStatusApiV1SystemStatusGetResponses];

export type HealthLiveHealthLiveGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type HealthLiveHealthLiveGetResponses = {
    /**
     * 请求成功
     */
    200: LiveStatus;
};

export type HealthLiveHealthLiveGetResponse = HealthLiveHealthLiveGetResponses[keyof HealthLiveHealthLiveGetResponses];

export type HealthReadyHealthReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type HealthReadyHealthReadyGetResponses = {
    /**
     * 请求成功
     */
    200: ReadinessStatus;
};

export type HealthReadyHealthReadyGetResponse = HealthReadyHealthReadyGetResponses[keyof HealthReadyHealthReadyGetResponses];
